# Site settings
title: Karl Fischer
email: fishi0x01@gmail.com
description: >
  A tech-blog about programming, automation and deployment.

baseurl: ""
url: "http://fishi.devtail.io"

encoding: UTF-8

# Media
github_username: fishi0x01
hackerrank_username: fishi0x01
leetcode_username: fishi0x01
hashicorp_username: fishi0x01
linkedin_username: fishi
keybaseio_username: fishi0x01
vagrantcloud_username: fishi0x01
cratesio_username: fishi0x01
hashnode_username: fishi0x01
stackoverflow_username: fishi0x01
stackoverflow_user_id: 4478420
duolingo_username: fishi0x01
memrise_username: fishi0x01
reddit_username: fishi0x01
goodreads_username: fishi0x01
meetup_id: 220542910
openhab_username: fishi0x01

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
github: [metadata]

plugins:
  - jekyll-gist
  - jekyll-redirect-from

whitelist:
  - jekyll-gist
  - jekyll-redirect-from
